name: Deploy to Pages

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install dependencies
        run: |
         npm ci

      - name: build site
        run: |
         git clone https://github.com/openkaios/openkaios-store-db.git db/
         node .
         cd db

      - name: Log files
        run: ls public
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          repository-name: openkaios/openkaios-store-db
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch